{
  try {
    callback.completed(context);
  }
 catch (  Exception x) {
    logger.info("Exception while notifying callback " + callback,x);
  }
catch (  Error x) {
    logger.info("Exception while notifying callback " + callback,x);
    throw x;
  }
}
