{
  try {
    fn(_value);
  }
 catch (  InterruptedException e) {
  }
}
